API:
  API_KEY: key3
  BASE_URL: http://localhost:11434/v1
  LARGE_LOGICAL_MODEL: hf.co/bartowski/Meta-Llama-3.1-8B-Instruct-GGUF:Q4_K_M
  LOGICAL_MODEL: hf.co/bartowski/Meta-Llama-3.1-8B-Instruct-GGUF:Q4_K_M
  QUANTIZATION_LARGE: gptq
  QUANTIZATION_SMALL: gptq
CLASSIFICATION:
  CLASSES: '[''negative'', ''positive'']'
  DESC: Classify whether the text (a movie review) is positive or negative.
  PREDICT_ON_WHOLE_SET_AT_THE_END: 'False'
PATH:
  DEFAULT_PROMPTS: ./prompts_classifier
  INPUT: ./imdb
  OUTPUT: ./classifier_output_interface
  PROMPTS: ./prompts_classifier
SYSTEM:
  CHUNK_SIZE: '900'
  COMPLETION_MODE: 'False'
  CONCURRENCY_LIMIT: '5'
  DOUBLE_CHECK_COUNTER: '1'
  MODE: api
  REQUIRED_ACCURACY: '0.9'
  STOP: 'True'
TRAINING:
  MAX_ITERS: '5'
  MODEL_PATH: distilbert-base-uncased
  TEST_SET_SIZE: '30'
  TRAIN_SET_INCREMENT: '100'
  TRAIN_SET_SIZE: '500'
  TRUNCATION_TYPE: head-tail
